name: GitHub Metrics 
on:
  schedule:
    - cron: '59 23 * * *'
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: lowlighter/metrics@v3.12
      with:
        token: ${{ secrets.METRICS_TOKEN }}
        committer_token: ${{ github.token }}
        committer_branch: master
        committer_message: Update metrics
        filename: metrics.svg
        repositories_forks: no
        repositories_affiliations: owner
        plugin_gists: yes
        plugin_reactions: yes
        plugin_reactions_details: percentage
        plugin_achievements: yes
        plugin_achievements_threshold: B
        plugin_achievements_ignored: explorer, automater, infographile, member
        plugin_languages: yes
        plugin_languages_details: bytes-size, percentage

