name: GitHub Metrics 
on:
  schedule:
    - cron: '59 23 * * 0'
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: lowlighter/metrics@v3.3
      with:
        plugin_achievements: yes
        plugin_achievements_threshold: B
        plugin_achievements_secrets: yes
        plugin_achievements_limit: 0

