name: GitHub Metrics 
on:
  schedule:
    - cron: '59 23 * * 0'
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: lowlighter/metrics@v3.3
      with:
        token: ${{ secrets.METRICS_TOKEN }}
        committer_token: ${{ github.token }}
        committer_branch: master
        committer_message: Update metrics
        filename: metrics.svg
        plugin_achievements: yes
        plugin_achievements_threshold: B
        plugin_achievements_secrets: yes
        plugin_achievements_limit: 0

