name: GitHub Metrics 
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ 'master' ]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - name: Check Month
      run: echo "::set-output name=MONTH::$(date +'%m')"
      id: check-month
    - run: echo "Month is '${{ steps.check-month.outputs.MONTH }}'"
    - uses: lowlighter/metrics@v3.12
      with:
        token: ${{ secrets.METRICS_TOKEN }}
        committer_token: ${{ github.token }}
        committer_branch: master
        committer_message: Update metrics
        filename: metrics.svg
        debug_flags: "${{ steps.check-month.outputs.MONTH == '10' && --halloween' || '' }}"
        repositories_forks: no
        repositories_affiliations: owner
        plugin_gists: yes
        plugin_reactions: yes
        plugin_reactions_details: percentage
        plugin_achievements: yes
        plugin_achievements_ignored: explorer, automater, infographile, member
        plugin_languages: yes
        plugin_languages_details: bytes-size, percentage
        plugin_discussions: yes

