name: GitHub Metrics 
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ 'master' ]
    paths:
      - .github/workflows/*.yml
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: zcong1993/setup-timezone@v1.1.2
      with:
        timezone: America/New_York
    - name: Check Month
      run: echo "::set-output name=MONTH::$(date '+%m')"
      id: check-month
    - run: echo "Month is '${{ steps.check-month.outputs.MONTH }}'"
    - uses: lowlighter/metrics@v3.17
      with:
        config_timezone: America/New_York
        token: ${{ secrets.METRICS_TOKEN }}
        committer_token: ${{ github.token }}
        committer_branch: metrics
        filename: metrics.svg
        plugins_errors_fatal: yes
        debug_flags: "${{ steps.check-month.outputs.MONTH == '10' && '--halloween' || '' }}"
        repositories_forks: no
        repositories_affiliations: owner
        base: header, repositories, metadata
        plugin_achievements: yes
        plugin_achievements_display: compact
        plugin_achievements_ignored: explorer, automater, infographile
        plugin_languages: yes
        plugin_languages_details: bytes-size, percentage
        plugin_discussions: yes

