on:
  workflow_dispatch:

jobs:
  languages:
    name: Languages
    runs-on: ubuntu-latest
    steps:
      - uses: spenserblack/github-polyglot/action@feature/github-action
        id: github-polyglot
        with:
          format: svg
